# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches: [ main ]


env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout CCI
        uses: actions/checkout@v2
        with:
          repository: conan-io/conan-center-index
          path: CCI
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: "pip3 install pyyaml"
      - name: Generate Job Matrix
        id: set-matrix
        run: |
          MATRIX=$(python3 main.py)
          echo "${MATRIX}"
          echo "::set-output name=matrix::${MATRIX}"
          
  check:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
      
    runs-on: ubuntu-20.04
    container: ${{ matrix.distro }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Python
        run: ${{ matrix.install-python}}
        
      - name: install conan
        run: pip3 install conan --ignore-installed
        
      - name: Checkout CCI
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: CCI
      - name: run
        shell: bash
        env:
          CONAN_SYSREQUIRES_MODE: enabled
          CONAN_SYSREQUIRES_SUDO: 0
        run: |
          conan install cmake/3.18.2@ -g virtualrunenv -b missing -s compiler.version=5 -s compiler.cppstd=11
          source ./activate_run.sh
          conan create CCI/recipes/${{ matrix.package }}/${{ matrix.folder }} ${{ matrix.package }}/system@

