# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches:
      - '**' 
  workflow_dispatch: {}


env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-20.04
    outputs:
      matrixLinux: ${{ steps.set-matrix.outputs.matrixLinux }}
      matrixBSD: ${{ steps.set-matrix.outputs.matrixBSD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: "pip3 install pyyaml requests aiohttp"
      - name: Generate Job Matrix
        id: set-matrix
        run: |
          python3 main.py
          MATRIXLINUX=$(cat matrixLinux.yml)
          echo "${MATRIXLINUX}"
          echo "::set-output name=matrixLinux::${MATRIXLINUX}"
          
          MATRIXBSD=$(cat matrixBSD.yml)
          echo "${MATRIXBSD}"
          echo "::set-output name=matrixBSD::${MATRIXBSD}"
  
  FreeBSD:
    if: ${{ false }}  # disable for now
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrixBSD)}}
      
    runs-on: macos-latest

    env:
      CC: clang
      CXX: clang++
      CONAN_SYSREQUIRES_MODE: enabled
    steps:
    - name: Checkout CCI
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.repo }}
        ref: ${{ matrix.ref }}
        path: CCI
    - name: run
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'CONAN_MAKE_PROGRAM CC CXX CONAN_SYSREQUIRES_MODE'
        usesh: true
        prepare: pkg install -y cmake py38-pip py38-sqlite3 sudo pkgconf
        run: |
          pip install conan
          code=0
          set +o pipefail
          conan create CCI/recipes/${{ matrix.package }}/${{ matrix.folder }} ${{ matrix.package }}/system@ || code=$?
          if [ $code == 6 ]
          then
            code=0
          fi
          exit "$code"
        
  Linux:
    if: ${{ false }}  # disable for now
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrixLinux)}}
      
    runs-on: ubuntu-20.04
    container: ${{ matrix.distro }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Python
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          case ${{ matrix.distro }} in
            opensuse*)
              zypper --non-interactive install python3 python3-pip python3-setuptools python3-wheel tar gzip gcc-c++ make;;
            debian*)
              apt-get update && apt-get -qq install -y --no-install-recommends python3-pip python3-setuptools pkg-config g++ make;;
            ubuntu*)
              apt-get update && apt-get -qq install -y --no-install-recommends python3-pip python3-setuptools pkg-config g++ make;;
            centos*)
              yum -y install dnf-plugins-core && yum config-manager --set-enabled powertools && yum install -y python3 python3-wheel python3-pip pkgconf-pkg-config gcc-c++ make;;
            archlinux*)
              pacman -Syu --noconfirm python-pip gcc pkgconf gcc make;;
            fedora*)
              dnf -y install python3 python3-wheel python3-pip pkgconf-pkg-config gcc-c++ make;;
          esac
        
      - name: install conan
        run: pip3 install --upgrade pip && pip3 install conan --ignore-installed
        
      - name: Checkout CCI
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: CCI
      - name: run
        shell: bash
        env:
          CONAN_SYSREQUIRES_MODE: enabled
          CONAN_SYSREQUIRES_SUDO: 0
          DEBIAN_FRONTEND: noninteractive
        run: |
          conan config install ${GITHUB_SERVER_URL}/${{ github.repository }}/archive/${{ github.sha }}.zip -sf=system-packages-checks-${{ github.sha }}/config 
          conan install cmake/3.18.2@ -g virtualrunenv -b missing -s compiler.version=5 -s compiler.cppstd=11
          source ./activate_run.sh
          code=0
          set +o pipefail
          conan create CCI/recipes/${{ matrix.package }}/${{ matrix.folder }} ${{ matrix.package }}/system@ || code=$?
          if [ $code == 6 ]
          then
            code=0
          fi
          exit "$code"

  Raspberry:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrixBSD)}}
      
    runs-on: ubuntu-latest

    env:
      CONAN_SYSREQUIRES_MODE: enabled
      CONAN_SYSREQUIRES_SUDO: 0
      DEBIAN_FRONTEND: noninteractive
    steps:
    - name: Checkout CCI
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.repo }}
        ref: ${{ matrix.ref }}
        path: CCI
    - name: run
      id: test
      uses: pguyot/arm-runner-action@v1
      with:
        commands: |
          #!/bin/bash
          apt-get update && apt-get -qq install -y --no-install-recommends python3-pip python3-setuptools pkg-config g++ make
          pip3 install --upgrade pip && pip3 install conan --ignore-installed
          code=0
          # set +o pipefail
          conan create CCI/recipes/${{ matrix.package }}/${{ matrix.folder }} ${{ matrix.package }}/system@ || code=$?
          if [ $code == 6 ]
          then
            code=0
          fi
          exit "$code"
