name: Prospector

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install prospector[with_mypy] prospector[with_vulture] types-requests types-python-dateutil types-PyYAML mypy vulture
        python -m pip install -r requirements.txt
    - name: Analysing the code with prospector
      run: prospector  --with-tool vulture  --with-tool mypy --strictness veryhigh --max-line-length 200 *.py
