name: Static Analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
      with:
        activate-environment: true
    - run: uv sync --locked
    - uses: astral-sh/ruff-action@v4.1.0
    - run: uv run ty check
